packages:
- packages/*
- docs

catalog:
  "@fedify/fedify": 1.9.0-dev.1516+8f42bff1
  "@js-temporal/polyfill": ^0.5.1
  "@logtape/logtape": ^1.0.4
  hono: ^4.8.2
  tsdown: ^0.12.8
  x-forwarded-fetch: ^0.2.0
