packages:
  - packages/*
  - docs
  - examples/rss-bot

allowBuilds:
  esbuild: true

linkWorkspacePackages: true

minimumReleaseAgeExclude:
  - "@fedify/*"
  - "@jsr/fedify__*"
  - markdown-it-jsr-ref@0.5.0

catalog:
  "@fedify/denokv": ~2.3.3
  "@fedify/fedify": ~2.3.3
  "@fedify/vocab": ~2.3.3
  "@fedify/vocab-runtime": ~2.3.3
  "@js-temporal/polyfill": ^0.5.1
  "@logtape/logtape": ^2.2.3
  hono: ^4.12.27
  tsdown: ^0.12.8
  x-forwarded-fetch: ^0.2.0
