// BotKit by Fedify: A framework for creating ActivityPub bots
// Copyright (C) 2025–2026 Hong Minhee <https://hongminhee.org/>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
import type { Context } from "@fedify/fedify/federation";

/**
 * The path pattern of local object URIs generated by BotKit 0.4 and earlier,
 * which did not carry the owning bot actor identifier.
 */
const legacyObjectPathPattern =
  /^\/ap\/(follow|create|article|chat-message|note|question|announce)\/([^/]+)$/;

/**
 * Rewrites a local object URI path in the legacy (pre-0.5) format, which did
 * not carry the owning bot actor identifier, into the canonical format nested
 * under the actor path.
 *
 * For example, `/ap/follow/123` becomes `/ap/actor/bot/follow/123` for the
 * identifier `bot`.
 * @param pathname The URL path to rewrite.
 * @param identifier The identifier of the bot actor that owns the legacy
 *                   objects.
 * @returns The rewritten path, or `null` if the path is not in the legacy
 *          object URI format.
 * @since 0.5.0
 */
export function rewriteLegacyObjectPath(
  pathname: string,
  identifier: string,
): string | null {
  const match = legacyObjectPathPattern.exec(pathname);
  if (match == null) return null;
  return `/ap/actor/${encodeURIComponent(identifier)}/${match[1]}/${match[2]}`;
}

/**
 * Parses a URI as a local ActivityPub resource, like
 * {@link Context.parseUri}, but additionally recognizes local object URIs in
 * the legacy (pre-0.5) format when a legacy bot actor identifier is
 * configured.
 *
 * Remote servers may have stored object URIs generated by BotKit 0.4 or
 * earlier and can send them back in later activities (e.g. `Accept`,
 * `Undo`, `Like`, or replies), so failing to parse them would break
 * long-lived interactions after an upgrade.  Since legacy URIs carry no
 * identifier, they can only be attributed to the single bot actor that
 * predates the upgrade.
 * @param ctx The Fedify context to parse the URI with.
 * @param uri The URI to parse.
 * @param legacyIdentifier The identifier of the bot actor that owns objects
 *                         with legacy URIs, or `undefined` if the instance
 *                         has no legacy objects.
 * @returns The parse result, or `null` if the URI is not a local resource.
 * @since 0.5.0
 */
export function parseLocalUri<TContextData>(
  ctx: Context<TContextData>,
  uri: URL | null,
  legacyIdentifier?: string,
): ReturnType<Context<TContextData>["parseUri"]> {
  if (uri == null) return null;
  const parsed = ctx.parseUri(uri);
  if (parsed != null) return parsed;
  if (legacyIdentifier == null) return null;
  const rewrittenPath = rewriteLegacyObjectPath(uri.pathname, legacyIdentifier);
  if (rewrittenPath == null) return null;
  const rewritten = new URL(uri.href);
  rewritten.pathname = rewrittenPath;
  return ctx.parseUri(rewritten);
}

/**
 * Keeps follow activities deliverable to actors hosted on this instance.
 * Remote recipients retain the usual exclusion of the instance's own inboxes.
 * @param ctx The federation context.
 * @param recipientId The recipient's actor URI.
 * @returns The delivery options for the follow activity.
 * @internal
 */
export function getFollowDeliveryOptions<TContextData>(
  ctx: Context<TContextData>,
  recipientId: URL | null,
): { excludeBaseUris: URL[] } {
  return {
    excludeBaseUris: ctx.parseUri(recipientId)?.type === "actor"
      ? []
      : [new URL(ctx.origin)],
  };
}
